"""
locustfile_worldcup.py  —  auto-generated by traffic_profile.py
Replays WorldCup98 request-rate profile as realistic Locust traffic.
"""
import csv
import os
import time
from locust import HttpUser, task


_PROFILE_PATH = os.path.join(os.path.dirname(__file__), "traffic_profile_test.csv")
_profile: list[tuple[int, float]] = []

with open(_PROFILE_PATH, newline="") as f:
    for row in csv.DictReader(f):
        _profile.append((int(row["second_offset"]), float(row["rps"])))

_TOTAL_SEC = _profile[-1][0] if _profile else 3600
_T0        = time.time()


def _current_target_rps() -> float:
    elapsed = (time.time() - _T0) % max(_TOTAL_SEC, 1)
    # Binary search for the right bucket
    lo, hi = 0, len(_profile) - 1
    while lo < hi:
        mid = (lo + hi + 1) // 2
        if _profile[mid][0] <= elapsed:
            lo = mid
        else:
            hi = mid - 1
    return max(_profile[lo][1], 0.1)


class WorldCupReplayUser(HttpUser):

    @task
    def hit_api(self):
        self.client.get("/api")

    def wait_time(self):
        return 1.0 / _current_target_rps()
