# Purpose: Docker orchestration configuration. Defines the scalable backend service and the static Nginx load balancer to distribute traffic.
# Usage: Execute to build and start the infrastructure.
services:
    server:
        build: .
        image: autoscaling-server
        expose:
            - "5000"


    nginx:
        image: nginx:alpine
        ports:  
          - "8080:80"
        
        volumes:
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

        depends_on:
          - server